---
server:
  port: ${SERVER_PORT_PRODUCTION}
spring:
  profile:
    active: production
  application:
    name: discovery-service
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE_URL_PRODUCTION}
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  datacenter: Bangalore
  environment: Production
#Enables all Actuator endpoints meant for monitoring,with basic authentication
#e.g: localhost:8181/spring-cloud-config-client/actuator/metrics
#Exposing 17 endpoint(s) beneath base path '/actuator' - See for this message in logs after applilcation start up to ensure actuator is enabled
management:
  endpoints:
    web:
      exposure:
        include: health, info
#For Distributed Tracing using Spring Cloud Sleuth
logging:
  level:
    root: ERROR
    org.springframework.cloud.sleuth: ERROR
    com.microservice: ERROR