security:
  oauth2:
    client:
      client-id: '{cipher}AgBFzjykjOU8mxkwTPs51Jzo4aoKqGreiZHf+7diymjjYe5i1nDkSrriHN39Tat27NDEnzomCLpBst4ZruhEpkaYZqaFp+IifL5BeCG3KkXyhOux3EqK3sBNRJC8BKWqoH+LalXCeohmnD999MQKibPN9AdKEEDkY/LqnMQw2yueMhn+OjTLPvJzXkdsU7pyPC8tDhVsSnPrMTrpg0mIC6L13A7Br4dc5ute/8LK742xi5eE8whyn8Wt4+MElWgCdf4U3oKK77hFr1lbQzkK9iP430BtvVhmHsP2yWwRoTHtU5jF8jqpqNBwJaIh6jURZkb6oBRrdC5BfO0etCMrVmLTBi9iLfBKy+DoKXsfMZpMqZDLuL2cGg4vBIeumNmjSDNhH03/tyLbgu059Ix7H8iXFAj4MyA5gR6YHEp+ndacLaK5UcX3Afasb6k4i8QSTCJ/psfQJoRxSOYKRGVFvkgHpVSurBE5DYpec/yhF4poeXH7blHDKkMCekx/SeqBkfobS1N80Lg1roEm+Hi9qUNIEYziXQK6FFVj8w7L+1k4rfU+nTC6YlmwP/HOKXentSAfcZzv9Lopv/gUFNY8gJjyfMO+2wlTbFEIQ+TpxxvRnH3TU7VNCeCrBALaB+vb7eqPsa5lnVrkSMHayGEZqqH15OV14FNCbOWkU8JQ1HtJy0sJv7yNmWXN/KdWXlRvvR+f9MYIrxtH8s1O/Ry6Rr52v7+8pp8oV28dldVU1X6i5Q=='
      client-secret: '{cipher}AgBBrLdfogB1xLU7HJTnBNiHko9NxrMJcQz0Sn9Wd/6VOnBG7b/4gDTZfH7QHKSOOnKgpRXEDk+PR8IKXoULfs6TU2iCAPQ+osusPfjerUi8Cf5fF/mGznyA5Ui1T2x3yW+bMTeE46qSPee+wreVjjHiahUaFbfgEAgH+9ma0eWmBIgMD2EU27uwvkG0itaA9FW0kHdg+s44ZiAWD9vbiQzfCNTvZY//Hw9iM3mbB14anqkCWKz3dP1F9c+AQ0lvgbnLYYBRtXy0QetPKVt1rrcmv7ZBtd4MlIs5iXnMKqJ6ovtdtXQI92SZDPLNkVKCJaXdmmwsT+npcR4qaAxJOgYBQj0LbLtlKmKcG2QkQ9U72wEc5i9G9SjSt7UOSOTjBT0Vg8mE+wp4suIqovF6DjWs42iHnUjRqeeD9xE7SOhOIG6/9SsIhsgW+toJLI3Xnml3CDbkPHKE8Fe5uR/gMX2LOtNfeYZC1dRk+nlL2kOIR8b5jjTiMmBmxRaKWeABpx/x66GB2pXY5b9slKtIm0uy/zsob/cCzaDpv/dY5jcPXZb81+HLQp3XMWbzfOR5nhAAOF/DFwyHmqyrHhRUTiHWWXfRgBNa+mzT3H4/Tq7mfMh10AeU33SP/rLZyJ5G5WC1f1yWHyam3iXnH9UKUvurs4CtMdao0qbqQw1pgBuub2flo3OYC9oxlnUHNvzBFVYrA6ncOhxCYAUhf1+5cpwzZdTYv5POQPLLpzmv+1lYdzqWvYHTwVoAUf9qTBPI48g='
      access-token-uri: https://dev-343895.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-343895.oktapreview.com/oauth2/default/v1/authorize
      scope:
      - 'openid'
      - 'profile'
      - 'email'
    resource:
      user-info-uri: https://dev-343895.oktapreview.com/oauth2/default/v1/userinfo
server:
  port: ${SERVER_PORT:8080}
spring:
  rabbitmq: #Using RabbitMQ for Spring cloud bus.
    host: '{cipher}AgCUXmhW2gCzd0JfK1uvXUW38OSZPohP2R30Tb0zQlbgIKsDpDyQkOh8c4qF0PWAbnBqyMLL9bnopR2LIeT2XSgS7H8R0xoj6UcE0l2raEPKU4zgp4z24xX5eHePL5/Ql2ysCl83wrFshWwTCI/hJSYRo30vnPgCxvGDfYj6kBFaTRgUUVNzeJ/iyGbRoLgmp1zEcdmv37s7Rtky3KiHHYX+GSOpbFoUDoXnihuQPTXoMYtn0SNlQwW8onJA1H4DLhmEMB7SZEX4A+LjEDae4SGcKX2SkGU0OomWKXQedhhuF/65l4zqaJI4H/XmNy7bsxZdZ5G3YkhqwFWcW7ORtFgrzjE4BdULshYfkG4NMRONQ0lx8BRNTkft/Ya/0IAAcQ2PrsxTrf7tmEtpI7JA+SI0lY9aW59EkKMBTNGbFwKzpVHFR15LGZGd1NVjDye1kZI3oPfvr+eeKWYRm3pGb9gDFN2eWVDNSbjpM4bArJolxtE+hf9Fnp/A25IxJVjNSyMWf2WeMmvHW2wiob9U0L/Z9bwUao/n6eVQ10FBo6slv/epQaFoJxw6EM1b77MBCoXpbZVSaAnhAtwzxgnBmysvBiIuCk6W0imq2immkQZIm+LD/19RWxqJtGPy8T0n4MplzptJzsg9gwQTdHhPN6vgqaMocH1prmtG+0sKOFR56V8BJ9Zuz43uQhVhBthaoFfjwcKrL2pO5FH4NJr2ClmD'
    port: '{cipher}AgAgFgIKl6RBLWhnlS0F0g2LPWtNbloolOrtOq+rUs14ADDb7BBzBBRcAD0ZtT6Zapl7y6G5jObYJN0Cme1sP6LKwDWucnQSLPHS7IttnnoB2uCoxSYU0fnuZZmRnH/72yQn/YzB865vGaXwuvYrHSqQRMhJen13T8VNJBHN74Ynb0xWgi8X3S9UQyx1The/rL2WV2eZFwVz30DFqawlf+SufCJJ0LLNL+ErL3sJaGcsQklVYFs7aws/HNUlagsyuBGwIr081UgNN1QDsqC/SKt06/R7nRs6TMU5TWDvbR3rNFlk7d4Zs3aFlHs/wTjk2OSU1hvLHkPPSQ0vrbrMUcP0IEuSczNDT6Xvrn593NLz9HEpZDDOD+cj9ahO8CvCEcGJfu2sGjzGJiiCtshxtk6Xjm5f2xCYp2u/500adeP1hRQTKuPyGtE4RQbngpYXm7KCQLD3lH8mo53nKjk3/uPspCPgIDuL82ixgJgvY8BVQtYry73dxXPllYhJNU4UPGZLrcrrhWqf9ut+PwmCMBT9UDPWytzDMOIK05htRa+kmwliB2TyB4NHbPq9bJP8iu+nDNznNMH6LZARLaNpXAOv2ZivNiZqzC15NGZUwT9Yn6fj3/ukPDY5SDGtiLikLy4Cd+qnFy4AcyKLgSP6dILP4tEs5Butx71RI8MI0Mx+RzEVcYu0GK8Znb88guFLH7UNKXFKibUGAvAlKgPl82v4'
    username: '{cipher}AgCcGmGlXDGNj2rS9xsMInFb8w3EosAQ2RTEICFb6yTKc8QdzSKkMCmA/k5xaDAUHptrz+wmJHwKfSu3tsNJ6tqKSRAc7HpZijBrNS99BizFTE0nMROHalv0dH1yYbgqQ+ReXkZSZloQZ2eYf949Cbhz/xC0uDrpT14bh+8i6SF29Pu/2rJILb1MzdvAuMwmEsFB1zXovJumSBvEjBEMlts9cp//QZcrZyK53CoWzH8NLZYZ73zX1gpUzMTZReiVDitqdlk9oX334W3+GxvzM9/VEexgiMJe7scvSh24ThdYkQHQi1tflIBseSI5en/ahbHSGHD/0b7PDnPjQg+CUpmIJbNDuXeb6TPAI8HyswcH87dVQxMQJ5J3EWhKPTL72JrO3NhBkVn+uPmnosmOJqmHvBXzGCHK00lK3CgkZiloUNYYLdqy1PM3UAf9wG3aQq5X/KKxP8qKRCiYx4c85gV2h5+dmPT2jsSe26EsfGndb3kOolhWGWrxPylPj2P+jgBuJKTNR9nC3jeXsIfRLoy9s81iE1R2VWp5Uu5GUMehGMtoonQ9J/ADZraJmE63irvTkb8tLOKWEF9Wqdog52erUmnM1XHT8HEF2Cb+GlgZ/sSxdLA4qLd58n2xxRERi5i0oIkYYofVapiAWdFHz4U3HN/+azjgXz9u9GcC4Lrki9tmSjw+RMr2NINJOXtAP5MysKrBFZ9qw9ryND5CKwjV'
    password: '{cipher}AgCcGmGlXDGNj2rS9xsMInFb8w3EosAQ2RTEICFb6yTKc8QdzSKkMCmA/k5xaDAUHptrz+wmJHwKfSu3tsNJ6tqKSRAc7HpZijBrNS99BizFTE0nMROHalv0dH1yYbgqQ+ReXkZSZloQZ2eYf949Cbhz/xC0uDrpT14bh+8i6SF29Pu/2rJILb1MzdvAuMwmEsFB1zXovJumSBvEjBEMlts9cp//QZcrZyK53CoWzH8NLZYZ73zX1gpUzMTZReiVDitqdlk9oX334W3+GxvzM9/VEexgiMJe7scvSh24ThdYkQHQi1tflIBseSI5en/ahbHSGHD/0b7PDnPjQg+CUpmIJbNDuXeb6TPAI8HyswcH87dVQxMQJ5J3EWhKPTL72JrO3NhBkVn+uPmnosmOJqmHvBXzGCHK00lK3CgkZiloUNYYLdqy1PM3UAf9wG3aQq5X/KKxP8qKRCiYx4c85gV2h5+dmPT2jsSe26EsfGndb3kOolhWGWrxPylPj2P+jgBuJKTNR9nC3jeXsIfRLoy9s81iE1R2VWp5Uu5GUMehGMtoonQ9J/ADZraJmE63irvTkb8tLOKWEF9Wqdog52erUmnM1XHT8HEF2Cb+GlgZ/sSxdLA4qLd58n2xxRERi5i0oIkYYofVapiAWdFHz4U3HN/+azjgXz9u9GcC4Lrki9tmSjw+RMr2NINJOXtAP5MysKrBFZ9qw9ryND5CKwjV'
#Eureka Service registry Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: '{cipher}AgCJZ/5XwbbKYNR2s1eVlekV1PUwvLccMJdzpL6rATxKQgWx2ZifTgETaRuMq9+GmcviYuY1EYCUO8Vdld5/G7fsDQVUqOI8Zsl6hNh7JOohkcbOEOsytSSXIHAGQDDw54At/YwEZUgpTh28RwaT5NLm7rPYJ7+tIvZP6Glec6LLv6SgQ8uyP+c0QPla5NH13wML+tpd5ZD+eiQ9TdhSPuftQpgAvlBhohDwRq8r4ipoAYByTa1nRoZiTJ2EU9Gdl0+o46uan1eA672N5p4mgqZIeTywv6Wn5j9vr1esj/TATiHznNk++A7E5aTyd3tW2OqX7Q0n+H9mr9q2xIf6RSMcv0cDZgomedjEe1q5VoytQ/m+AtlWiiidci2E1OYgjYPpRy+i4cyAz+ckpjcwia+SGQL3Utrx1TpZJZqNoAS/RGQITYc+R14k89ohqIaLeIrvYhjiPMBgq/v80UEn+G2gb+zCRZApQCABaEy66wFmV8b/gW6Dce4pKJ1jXbzTGoQnZEzcsjaHYycxL4ZuDDRzuu0LYFBX9F6pbBEqDUuDI6+eo634guayaS41EkwQyaMQPH8S2CgStlAEPBwFx9fsISOQ2VdDr2jhynVBECsJ0cAnkCUR2gu/59aNvjLXsT/I0JuiE1NpLMCoBerWiHyTFyotwH9bG91FqGv/HihB4ZbU+un1YPcO0L30ALfm83dU8e8H72CZtlazCGnkDbosGDNafGmULu3448AOai3w3A=='
  instance:
      # The default 'instance id' won't be unique if running on the same host and using 'server.port=0'
      # By Default, The default application name (that is, the service ID),
      # are ${spring.application.name}, and ${server.port}, respectively and is suffice for production
      instance-id: ${spring.application.name}:${random.int[1,99]}
      hostname: localhost
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 126000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  eureka:
    enabled: true
zuul:
  ignored-services: "*" #To skip having a service automatically added, set zuul.ignored-services to a list of service id pattern
  #prefix: /toll-system #To add a prefix to all mappings.This is Global prefix
  routes:
    toll-platform-web:
      path: /toll-platform-web/**
      serviceId: toll-platform-web
      sensitive-headers:
      stripPrefix: false      
  ignored-patterns:
    "/toll-platform-web/toll-web/admin" # Does not allow this path to be accessed.
#Actuator Endpoint config
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,hystrix.stream}
#For Distributed Tracing using Spring Cloud Sleuth and log level config
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: ERROR
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.boot.devtools: WARN
    com.microservice: INFO
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}