server:
  port: ${SERVER_PORT:8761}
spring:
  application:
    name: discovery-service  
eureka:
  instance:
    hostname: localhost 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0  
  datacenter: Bangalore
  environment: Development