---
server:
  port: ${SERVER_PORT_STAGING}
spring:
  profile:
    active: Staging
  application:
    name: discovery-service
  rabbitmq: #Using RabbitMQ for Spring cloud bus.
    host: ${RABBITMQ_CLUSTER_STAGING}
    port: ${RABBITMQ_PORT_STAGING}
    username: ${RABBITMQ_USERNAME_STAGING}
    password: ${RABBITMQ_PASSWORD_STAGING}
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE_URL_STAGING}
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  datacenter: Bangalore
  environment: Staging
#Enables all Actuator endpoints meant for monitoring,
#e.g: localhost:8181/spring-cloud-config-client/actuator/metrics
#Exposing 17 endpoint(s) beneath base path '/actuator' - See for this message in logs after applilcation start up to ensure actuator is enabled
management:
  endpoints:
    web:
      exposure:
        include: "*"
#For Distributed Tracing using Spring Cloud Sleuth
logging:
  level:
    root: ERROR
    org.springframework.cloud.sleuth: ERROR
    com.microservice: ERROR