---
server:
  port: ${SERVER_PORT:8761}
spring:
  profile:
    active: development
  application:
    name: discovery-service
  rabbitmq:
    host: ${RABBITMQ_HOST_DEV:192.168.99.100} #RabbitMQ running as docker container
    port: ${RABBITMQ_PORT_DEV:5672}
    username: ${RABBITMQ_USERNAME_DEV:guest}
    password: ${RABBITMQ_PASSWORD_DEV:guest}
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE_URL_STAGING:http://localhost:8761/eureka/}
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  datacenter: Bangalore
  environment: Development
#Enables all Actuator endpoints meant for monitoring,
#e.g: localhost:8181/spring-cloud-config-client/actuator/metrics
#Exposing 17 endpoint(s) beneath base path '/actuator' - See for this message in logs after applilcation start up to ensure actuator is enabled
management:
  endpoints:
    web:
      exposure:
        include: "*"
#For Distributed Tracing using Spring Cloud Sleuth
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: INFO
    com.microservice: DEBUG